#!/usr/bin/env bash

# -help
# ettl INFO /home/pi/dev/expose-to-the-light/logs/ --imagesBasePath /home/pi/dev/expose-to-the-light/captured-images/ --setSettings --numberOfCaptures 5 --intervalSeconds 5 --rawFileExtension CR2

artif="expose-to-the-light_2.13-0.1.17.jar"
vm_options="-Djna.library.path="
export LOG_LEVEL=$1
export LOG_LOCATION=$2
export JDK_JAVA_OPTIONS=$vm_options

shift 2

echo "Starting application..."
java -jar "$artif" "$@"
